export class Participant {
  constructor(name: string) {
    this.name = name;
  }

  static participants: Participant[] = [
    new Participant('Fernando Gordillo'),
    new Participant('Alvaro Leiva'),
    new Participant('Ronald Canchanya'),
    new Participant('Paul Zacarias'),
    new Participant('Daniel Erazo'),
    new Participant('Eddy Flores'),
    new Participant('Daniel Olano'),
    new Participant('Anthony Mateo'),
    new Participant('Claudia Gamarra'),
    new Participant('Kenny Moncada'),
    new Participant('Carlos Araujo'),
    new Participant('Doris Arraiza'),
    new Participant('Giovanna Haro'),
    new Participant('Giancarlo Bedoya'),
    new Participant('Ronald Ramirez'),
    new Participant('Diego Cumpa'),
    new Participant('Peter Caceres'),
    new Participant('Andherson'),
    new Participant('Victor Grimaldo'),
    new Participant('Kendy Otiniano'),
    new Participant('Luis Huapaya'),
    new Participant('Paolo Ortega'),
    new Participant('Oscar Cossio'),
    new Participant('Percy Romero'),
    new Participant('Pamela Espinoza'),
    new Participant('Randy'),
    new Participant('Liliana'),
    new Participant('Jhony'),
    new Participant('Luis Rosales'),
    new Participant('Gonzalo Diaz'),
    new Participant('Kenny Tafur'),
    new Participant('Julius Ñahuero'),
    new Participant('Rodrigo Cornejo'),
    new Participant('Bonny'),
    new Participant('Isamar'),
    new Participant('Emperatriz'),
    new Participant('Marilu'),
    new Participant('Kassey'),
    new Participant('Ivonne'),
    new Participant('Jose Marchena'),
    new Participant('Juan Jose'),
    new Participant('Fernando Tito'),
    new Participant('Giancarlo Chiappe'),
    new Participant('Wilmer Salazar'),
    new Participant('Gerardo Camino'),
    new Participant('Braulio Vargas'),
    new Participant('Alejandro Vasquez'),
    new Participant('Julio Ruiz'),
    new Participant('Renzo Paredes'),
    new Participant('Carlos Begazo'),
    new Participant('Luis Diaz'),
    new Participant('Paulo Luzquiños'),
    new Participant('Franco Condor'),
    new Participant('Javier Reategui'),
    new Participant('Carlos Villanueva'),
    new Participant('Jose Urquieta'),
    new Participant('Amado Millones'),
    new Participant('Javier Urquiza'),
    new Participant('Manuel Samanez'),
    new Participant('Jose Fernandez'),
    new Participant('Luis Millones'),
    new Participant('Richard Champoñan'),
    new Participant('Mafer'),
    new Participant('JuanDiego Aranda'),
    new Participant('Rogger Aburto'),
    new Participant('Josh'),
    new Participant('Andre Hurtado'),
    new Participant('Raul Ortiz'),
    new Participant('Christian Sanchez'),
    new Participant('Alex Lozano'),
    new Participant('Kevin Alvarez'),
    new Participant('Diana Vidal'),
    new Participant('Edith Menor'),
    new Participant('Katherine Medrano'),
    new Participant('Lisset Juarez'),
    new Participant('Adriana Martinez'),
    new Participant('Lester Lozano'),
    new Participant('Franklin Pajuelo'),
    new Participant('Eduardo Mendoza'),
    new Participant('Evelyn Ayala'),
    new Participant('Lisbeth Gonzales'),
    new Participant('Stephanie Flores'),
    new Participant('Nahomi Rodriguez'),
    new Participant('Felix Arenas'),
    new Participant('Michael Olaya'),
    new Participant('Michael Castillo'),
    new Participant('Lucero Vilchez'),
    new Participant('Marian Suarez'),
    new Participant('Katherine Nolazco'),
    new Participant('Yindri Bastidas'),
    new Participant('Hector Sanchez'),
    new Participant('Liliana Ibarguen'),
    new Participant('Vanessa Vilchez'),
    new Participant('Cynthia Sernaque'),
    new Participant('Eddy Peña'),
    new Participant('Marco Ravello'),
    new Participant('Luisa Flores'),
    new Participant('Claudia Ulloa'),
    new Participant('Marianella Becerra'),
    new Participant('Stephanie Meneses'),
    new Participant('Gustavo Roque'),
    new Participant('Daniela Roque'),
    new Participant('Giovanny Fonseca'),
    new Participant('Diana Vasquez'),
    new Participant('Nery Talledo'),
    new Participant('Hadit Talledo'),
    new Participant('Katesbeth Talledo'),
    new Participant('Naty Talledo'),
    new Participant('Rocio Echevarria'),
    new Participant('Freddy Candiotti'),
    new Participant('Roger Talledo'),
    new Participant('Renan Roque'),
    new Participant('Bernabe Roque'),
    new Participant('Edith Roque'),
    new Participant('Manuel Parinango'),
    new Participant('Luciana Parinango'),
    new Participant('Robert Cruzalegui'),
    new Participant('Sindy Cruzalegui'),
    new Participant('Margarita Huamancondor'),
    new Participant('Luis Roque'),
    new Participant('Natividad Nores'),
    new Participant('Cerapio Roque'),
    new Participant('Doris Peña'),
    new Participant('Sergio Roque'),
    new Participant('Mariella Romero'),
    new Participant('Omar Pacherrez'),
    new Participant('Leo'),
    new Participant('Lee Rosales'),
    new Participant('Jonathan Lopez'),
    new Participant('Elvis Rupire'),
    new Participant('Herberth Corazao'),
    new Participant('Raul Perales'),
    new Participant('Teddy bautista'),
    new Participant('Jose Huerta'),
    new Participant('Juan Carlos Correa'),
    new Participant('Alex Leo'),
    new Participant('Daniela Leo'),
    new Participant('Daniela Andrade'),
    new Participant('Gonzalo Diaz'),
    new Participant('Gladys Valentin'),
    new Participant('Iris Villegas'),
    new Participant('Mayumi'),
    new Participant('Steph Morzan'),
    new Participant('Walter Pinedo'),
    new Participant('Herberth Corazao'),
    new Participant('Alejandra Fuertes'),
    new Participant('Elita Ruiz'),
    new Participant('Andrea Ruiz'),
    new Participant('Diego Ruiz'),
    new Participant('Elita Karen Ruiz'),
    new Participant('Lucia Ruiz'),
    new Participant('Yngrith Grozzo'),
    new Participant('Mary Sanchez'),
    new Participant('Flor Tamayo'),
    new Participant('Miguel Yoshida'),
    new Participant('Promo80 =)')
  ];
  id: number;
  name: string;
}
